version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
  heroku: circleci/heroku@0.0.10

jobs:
  build:
    parallelism: 3
    docker:
      - image: circleci/ruby:2.7.2
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: truck_on_test
    environment:
      BUNDLE_PATH: vendor/bundle
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      PGHOST: 127.0.0.1
      PGUSER: postgres
      RAILS_ENV: test
    executor: ruby/default
    steps:
      - checkout
      - run: cp config/database.yml.ci config/database.yml
      - run:
          name: Bundler Version
          command: bundle -v
      - run:
          name: Build gemfile
          command: bundle install
      - run:
          name: Setup DB
          command: bundle exec rails db:schema:load --trace
      - run:
          name: Seed DB
          command: bundle exec rails db:{migrate,seed}
      - run:
          name: Load CSV file to DB
          command: bundle exec rails csv_load:all
      - run:
          name: Run test suite
          command: bundle exec rspec

  deploy:
    machine:
        enabled: true
    # working_directory: ~/circleci-demo-workflows
    environment:
      HEROKU_APP: $HEROKU_APP_NAME
    steps:
      - checkout
      # - run:
      #     name: Setup Heroku
      #     command: bash .circleci/setup-heroku.sh # run a script to set up Heroku

      - run:
          command: |
            git push heroku main
            heroku run rake db:{migrate,seed}
            heroku run rake csv_load:all
            sleep 5 # sleep for 5 seconds to wait for dynos
            heroku restart

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
